### ISSUE TITLE
May rank all candidate instructions for given examples with GPT-4?

### ISSUE THREAD

**Issue by skykiseki** [ytyz1307zzh/Auto-Instruct#4]
I still wonder why it needs to train a specific model to rank the instructions? Can GPT-4 be the ranker with a prompt templete?

**Comment by txy77** [comment]
I think it aims to reduce the cost of evaluating the prompt. You don't need to go through a validation dataset to evaluate a prompt.

**Comment by skykiseki** [comment]
> I think it aims to reduce the cost of evaluating the prompt. You don't need to go through a validation dataset to evaluate a prompt.

ok
