### ISSUE TITLE
gpt-utils.py

### ISSUE THREAD

**Issue by zxqSled** [ytyz1307zzh/Auto-Instruct#6]
Hello,how can i use my own openai-key in gpt-utils.py, i always get HTTPError:500 in result.
When I replace the openai.api in the "Authorization: Bearer" line of the script with my own key, the message in response  is still "You didn't provide an API key. You need to provide your API key in an Authorization header".
how can i deal with it?
Thank you very much!!!

**Comment by ytyz1307zzh** [comment]
Hi, could you specify which script you are trying to run? `gpt_utils.py` is not meant to be directly run. Instead, it should be imported to other scripts. Did you provide the API key in the command line arguments?

**Comment by zxqSled** [comment]
Hello,i try to run gpt3_instruction_generation.py,but it reported an error and traced back to gpt_ utils.py. I have provided api kei with -api_key = "****",is it right?I just modified the content in the request header "https://api.openai.com" ,or the error message "[Errno 101] Network is unreachable" will in return, but after I make the changes, the error message "HTTPError: 500 Server Error" will appear. When I click on the link, it will prompt me that I did not provide an apikey...Could you give me some help or advice,thanks very much!!

**Comment by ytyz1307zzh** [comment]
Hi, suppose your API key is ABCDE, you just need to append "-api_key ABCDE" to your Python command.

**Comment by zxqSled** [comment]
Hi,i know it's a network issue with the server , thanks for your reply!!!!!

**Comment by ytyz1307zzh** [comment]
No problem!
